apiVersion: v1
kind: Service
metadata:
  name: cloud-dashboard
spec:
  type: NodePort
  selector:
    app: cloud-dashboard
  ports:
    - port: 5000         # inside cluster
      targetPort: 5000   # container port
      nodePort: 30007    # external access port

